version: "3"
services:
  client:
    image: dartungar/bitcoin-wallet-client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8043:80
    depends_on:
      - api
      - db

  api:
    image: dartungar/bitcoin-wallet-api
    restart: unless-stopped
    env_file:
      - .env
    command: pipenv run uvicorn service:app 
    ports:
      - 5001:5000
    depends_on:
      - db
  db:
    image: dartungar/bitcoin-wallet-db
    container_name: bitcoin-wallet-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5431:5432