version: "3"
services:

  client:
    image: dartungar/bitcoin-wallet-client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - api
      - db

  api:
    image: dartungar/bitcoin-wallet-api
    container_name: bitcoin-wallet-api
    restart: unless-stopped
    env_file:
      - .env
    command: pipenv run uvicorn service:app --host 0.0.0.0
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: dartungar/bitcoin-wallet-db
    container_name: bitcoin-wallet-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5431:5432